import type { SynergyRule } from '../types/synergy.js';

export const SYNERGY_RULES: SynergyRule[] = [
  // ─── ANIMAL SYNERGIES ─────────────────────────────────────────────────────

  {
    id: 'animal_3',
    name: 'Pack Instinct',
    description: '3 Animals: +20% Attack Speed',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'animal', minCount: 3 }],
    effects: [{ type: 'stat_multiply', stat: 'speed', multiplier: 1.2 }],
    stackable: false,
  },
  {
    id: 'animal_5',
    name: 'Beast Horde',
    description: '5 Animals: +50% Damage',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'animal', minCount: 5 }],
    effects: [{ type: 'stat_multiply', stat: 'attack', multiplier: 1.5 }],
    stackable: false,
  },
  {
    id: 'animal_africa',
    name: 'Savanna Fury',
    description: '3 Animals + Africa: Lifesteal aura',
    tier: 'silver',
    conditions: [
      { type: 'has_tag', tag: 'animal', minCount: 3 },
      { type: 'has_tag', tag: 'africa', minCount: 1 },
    ],
    effects: [{ type: 'lifesteal', fraction: 0.15 }],
    stackable: false,
  },
  {
    id: 'animal_africa_herbivore',
    name: 'Savanna Survivor',
    description: '5 Animals + Africa + Herbivore: Massive regen tank build',
    tier: 'gold',
    conditions: [
      { type: 'has_tag', tag: 'animal', minCount: 5 },
      { type: 'has_tag', tag: 'africa', minCount: 1 },
      { type: 'has_tag', tag: 'herbivore', minCount: 1 },
    ],
    effects: [
      { type: 'regen', hpPerTick: 8 },
      { type: 'stat_multiply', stat: 'health', multiplier: 1.5 },
    ],
    stackable: false,
  },
  {
    id: 'predator_3',
    name: 'Apex Hunter',
    description: '3 Predators: Execute enemies below 20% HP',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'predator', minCount: 3 }],
    effects: [{ type: 'execute_low_hp', hpThresholdFraction: 0.2 }],
    stackable: false,
  },
  {
    id: 'predator_5',
    name: 'Apex Legion',
    description: '5 Predators: Execute + 30% Attack',
    tier: 'gold',
    conditions: [{ type: 'has_tag', tag: 'predator', minCount: 5 }],
    effects: [
      { type: 'execute_low_hp', hpThresholdFraction: 0.25 },
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.3 },
    ],
    stackable: false,
  },
  {
    id: 'herbivore_3',
    name: 'Grazer Shield',
    description: '3 Herbivores: Defensive scaling (+30% Health)',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'herbivore', minCount: 3 }],
    effects: [{ type: 'stat_multiply', stat: 'health', multiplier: 1.3 }],
    stackable: false,
  },
  {
    id: 'herbivore_5',
    name: 'Fortress of Nature',
    description: '5 Herbivores: +50% Health + Regen',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'herbivore', minCount: 5 }],
    effects: [
      { type: 'stat_multiply', stat: 'health', multiplier: 1.5 },
      { type: 'regen', hpPerTick: 5 },
    ],
    stackable: false,
  },
  {
    id: 'fast_3',
    name: 'Blur Rush',
    description: '3 Fast cards: +30% Speed',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'fast', minCount: 3 }],
    effects: [{ type: 'stat_multiply', stat: 'speed', multiplier: 1.3 }],
    stackable: false,
  },
  {
    id: 'fast_5',
    name: 'Lightspeed',
    description: '5 Fast cards: Double attack frequency',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'fast', minCount: 5 }],
    effects: [{ type: 'stat_multiply', stat: 'speed', multiplier: 2.0 }],
    stackable: false,
  },
  {
    id: 'predator_fast_assassin',
    name: 'Shadow Assassin',
    description: '2 Predators + 3 Fast: Burst damage build',
    tier: 'gold',
    conditions: [
      { type: 'has_tag', tag: 'predator', minCount: 2 },
      { type: 'has_tag', tag: 'fast', minCount: 3 },
    ],
    effects: [
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.4 },
      { type: 'stat_multiply', stat: 'speed', multiplier: 1.5 },
      { type: 'crit_chance', chance: 0.25 },
    ],
    stackable: false,
  },
  {
    id: 'feline_5',
    name: 'Pride of Kings',
    description: '5 Felines: +40% Attack, Lifesteal',
    tier: 'gold',
    conditions: [{ type: 'has_tag', tag: 'feline', minCount: 5 }],
    effects: [
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.4 },
      { type: 'lifesteal', fraction: 0.2 },
    ],
    stackable: false,
  },
  {
    id: 'mammal_5',
    name: 'Warm Blood',
    description: '5 Mammals: +20% all stats',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'mammal', minCount: 5 }],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.2 }],
    stackable: false,
  },

  // ─── HUMAN SYNERGIES ──────────────────────────────────────────────────────

  {
    id: 'human_5',
    name: 'Human Spirit',
    description: '5 Humans: +30% Critical Chance',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'human', minCount: 5 }],
    effects: [{ type: 'crit_chance', chance: 0.3 }],
    stackable: false,
  },
  {
    id: 'human_economy',
    name: 'Merchants Guild',
    description: '3 Humans + Economics: Coin gain per battle',
    tier: 'silver',
    conditions: [
      { type: 'has_tag', tag: 'human', minCount: 3 },
      { type: 'has_tag', tag: 'economics', minCount: 1 },
    ],
    effects: [{ type: 'coin_gain_per_battle', amount: 25 }],
    stackable: false,
  },
  {
    id: 'human_war',
    name: 'War Veterans',
    description: '3 Humans + War: +25% Attack',
    tier: 'bronze',
    conditions: [
      { type: 'has_tag', tag: 'human', minCount: 3 },
      { type: 'has_tag', tag: 'war', minCount: 1 },
    ],
    effects: [{ type: 'stat_multiply', stat: 'attack', multiplier: 1.25 }],
    stackable: false,
  },
  {
    id: 'human_science',
    name: 'Scientific Method',
    description: '3 Humans + Science: +20% all stats',
    tier: 'silver',
    conditions: [
      { type: 'has_tag', tag: 'human', minCount: 3 },
      { type: 'has_tag', tag: 'science', minCount: 1 },
    ],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.2 }],
    stackable: false,
  },
  {
    id: 'royalty_3',
    name: 'Royal Court',
    description: '3 Royalty: +35% Health, Shield',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'royalty', minCount: 3 }],
    effects: [
      { type: 'stat_multiply', stat: 'health', multiplier: 1.35 },
      { type: 'shield', flatAmount: 200 },
    ],
    stackable: false,
  },
  {
    id: 'military_5',
    name: 'Standing Army',
    description: '5 Military: +40% Attack, +20% Health',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'military', minCount: 5 }],
    effects: [
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.4 },
      { type: 'stat_multiply', stat: 'health', multiplier: 1.2 },
    ],
    stackable: false,
  },

  // ─── EVENT SYNERGIES ──────────────────────────────────────────────────────

  {
    id: 'event_5',
    name: 'Historical Impact',
    description: '5 Events: AoE damage boost',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'event', minCount: 5 }],
    effects: [{ type: 'aoe_damage', damagePerTick: 10 }],
    stackable: false,
  },
  {
    id: 'war_5',
    name: 'Theater of War',
    description: '5 War events: +50% Attack, AoE',
    tier: 'gold',
    conditions: [{ type: 'has_tag', tag: 'war', minCount: 5 }],
    effects: [
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.5 },
      { type: 'aoe_damage', damagePerTick: 15 },
    ],
    stackable: false,
  },
  {
    id: 'war_economy',
    name: 'War Profiteer',
    description: 'War + Economics: Bonus raid rewards & coin gain',
    tier: 'silver',
    conditions: [
      { type: 'has_tag', tag: 'war', minCount: 2 },
      { type: 'has_tag', tag: 'economics', minCount: 1 },
    ],
    effects: [
      { type: 'coin_gain_per_battle', amount: 30 },
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.15 },
    ],
    stackable: false,
  },

  // ─── SCIENCE SYNERGIES ────────────────────────────────────────────────────

  {
    id: 'science_5',
    name: 'Laboratory',
    description: '5 Science: +30% all stats',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'science', minCount: 5 }],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.3 }],
    stackable: false,
  },
  {
    id: 'war_science_europe',
    name: 'Tech Artillery',
    description: 'War + Science + Europe: Crit scaling build',
    tier: 'gold',
    conditions: [
      { type: 'has_tag', tag: 'war', minCount: 3 },
      { type: 'has_tag', tag: 'science', minCount: 1 },
      { type: 'has_tag', tag: 'europe', minCount: 1 },
    ],
    effects: [
      { type: 'crit_chance', chance: 0.35 },
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.4 },
    ],
    stackable: false,
  },
  {
    id: 'war_science',
    name: 'Military R&D',
    description: '3 War + 2 Science: Crit scaling',
    tier: 'silver',
    conditions: [
      { type: 'has_tag', tag: 'war', minCount: 3 },
      { type: 'has_tag', tag: 'science', minCount: 2 },
    ],
    effects: [
      { type: 'crit_chance', chance: 0.2 },
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.25 },
    ],
    stackable: false,
  },
  {
    id: 'physics_5',
    name: 'Force of Nature',
    description: '5 Physics: +60% Attack',
    tier: 'gold',
    conditions: [{ type: 'has_tag', tag: 'physics', minCount: 5 }],
    effects: [{ type: 'stat_multiply', stat: 'attack', multiplier: 1.6 }],
    stackable: false,
  },
  {
    id: 'mathematics_3',
    name: 'Calculated Strike',
    description: '3 Mathematics: +25% Crit',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'mathematics', minCount: 3 }],
    effects: [{ type: 'crit_chance', chance: 0.25 }],
    stackable: false,
  },

  // ─── POLITICS & ECONOMICS ─────────────────────────────────────────────────

  {
    id: 'politics_5',
    name: 'Political Power',
    description: '5 Politics: +25% all stats',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'politics', minCount: 5 }],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.25 }],
    stackable: false,
  },
  {
    id: 'economics_5',
    name: 'Global Market',
    description: '5 Economics: Large coin gain per battle',
    tier: 'gold',
    conditions: [{ type: 'has_tag', tag: 'economics', minCount: 5 }],
    effects: [
      { type: 'coin_gain_per_battle', amount: 75 },
      { type: 'stat_multiply', stat: 'all', multiplier: 1.15 },
    ],
    stackable: false,
  },
  {
    id: 'human_economy_3',
    name: 'Trade Route',
    description: '3 Humans + 2 Economics: Coin gain + stat boost',
    tier: 'silver',
    conditions: [
      { type: 'has_tag', tag: 'human', minCount: 3 },
      { type: 'has_tag', tag: 'economics', minCount: 2 },
    ],
    effects: [
      { type: 'coin_gain_per_battle', amount: 20 },
      { type: 'stat_multiply', stat: 'all', multiplier: 1.1 },
    ],
    stackable: false,
  },

  // ─── REGIONAL SYNERGIES ───────────────────────────────────────────────────

  {
    id: 'europe_5',
    name: 'European Dominion',
    description: '5 Europe: +30% all stats',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'europe', minCount: 5 }],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.3 }],
    stackable: false,
  },
  {
    id: 'asia_5',
    name: 'Eastern Wisdom',
    description: '5 Asia: +25% all stats, Regen',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'asia', minCount: 5 }],
    effects: [
      { type: 'stat_multiply', stat: 'all', multiplier: 1.25 },
      { type: 'regen', hpPerTick: 3 },
    ],
    stackable: false,
  },
  {
    id: 'africa_5',
    name: 'Heart of the Continent',
    description: '5 Africa: +35% Health, Regen',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'africa', minCount: 5 }],
    effects: [
      { type: 'stat_multiply', stat: 'health', multiplier: 1.35 },
      { type: 'regen', hpPerTick: 6 },
    ],
    stackable: false,
  },
  {
    id: 'russia_3',
    name: 'Iron Curtain',
    description: '3 Russia: +30% Health',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'russia', minCount: 3 }],
    effects: [{ type: 'stat_multiply', stat: 'health', multiplier: 1.3 }],
    stackable: false,
  },
  {
    id: 'japan_3',
    name: 'Bushido',
    description: '3 Japan: +30% Speed, +15% Attack',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'japan', minCount: 3 }],
    effects: [
      { type: 'stat_multiply', stat: 'speed', multiplier: 1.3 },
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.15 },
    ],
    stackable: false,
  },
  {
    id: 'china_3',
    name: 'Middle Kingdom',
    description: '3 China: +25% all stats',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'china', minCount: 3 }],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.25 }],
    stackable: false,
  },
  {
    id: 'rome_3',
    name: 'Pax Romana',
    description: '3 Rome: +20% Attack, Shield',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'rome', minCount: 3 }],
    effects: [
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.2 },
      { type: 'shield', flatAmount: 150 },
    ],
    stackable: false,
  },
  {
    id: 'persia_3',
    name: 'Persian Empire',
    description: '3 Persia: +20% all stats',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'persia', minCount: 3 }],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.2 }],
    stackable: false,
  },
  {
    id: 'greece_3',
    name: 'Olympian',
    description: '3 Greece: +25% Speed, Crit',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'greece', minCount: 3 }],
    effects: [
      { type: 'stat_multiply', stat: 'speed', multiplier: 1.25 },
      { type: 'crit_chance', chance: 0.15 },
    ],
    stackable: false,
  },

  // ─── RARITY SYNERGIES ─────────────────────────────────────────────────────

  {
    id: 'all_mr',
    name: 'Pantheon',
    description: 'All 5 cards are MR: 3× CP multiplier',
    tier: 'gold',
    conditions: [{ type: 'has_rarity', rarity: 'MR', minCount: 5 }],
    effects: [{ type: 'cp_multiply', multiplier: 3.0 }],
    stackable: false,
  },
  {
    id: 'all_ur',
    name: 'Elites',
    description: 'All 5 cards are UR+: 2× CP multiplier',
    tier: 'gold',
    conditions: [{ type: 'has_rarity', rarity: 'UR', minCount: 5 }],
    effects: [{ type: 'cp_multiply', multiplier: 2.0 }],
    stackable: false,
  },
  {
    id: 'all_ssr',
    name: 'Champions',
    description: 'All 5 cards are SSR+: 1.5× CP',
    tier: 'gold',
    conditions: [{ type: 'has_rarity', rarity: 'SSR', minCount: 5 }],
    effects: [{ type: 'cp_multiply', multiplier: 1.5 }],
    stackable: false,
  },
  {
    id: 'mixed_foil',
    name: 'Foil Collection',
    description: '3+ SSR or MR cards: +20% all stats',
    tier: 'silver',
    conditions: [
      { type: 'has_rarity', rarity: 'SSR', minCount: 3 },
    ],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.2 }],
    stackable: false,
  },

  // ─── ART & CULTURE ────────────────────────────────────────────────────────

  {
    id: 'art_5',
    name: 'Renaissance',
    description: '5 Art: +25% Speed, Coin gain',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'art', minCount: 5 }],
    effects: [
      { type: 'stat_multiply', stat: 'speed', multiplier: 1.25 },
      { type: 'coin_gain_per_battle', amount: 15 },
    ],
    stackable: false,
  },
  {
    id: 'music_3',
    name: 'Battle Hymn',
    description: '3 Music: +20% Speed',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'music', minCount: 3 }],
    effects: [{ type: 'stat_multiply', stat: 'speed', multiplier: 1.2 }],
    stackable: false,
  },
  {
    id: 'philosophy_3',
    name: 'Socratic Method',
    description: '3 Philosophy: +15% all stats',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'philosophy', minCount: 3 }],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.15 }],
    stackable: false,
  },
  {
    id: 'mythology_3',
    name: 'Gods of Old',
    description: '3 Mythology: +30% Attack, Shield',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'mythology', minCount: 3 }],
    effects: [
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.3 },
      { type: 'shield', flatAmount: 200 },
    ],
    stackable: false,
  },
  {
    id: 'religion_5',
    name: 'Holy War',
    description: '5 Religion: +40% Health, Regen',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'religion', minCount: 5 }],
    effects: [
      { type: 'stat_multiply', stat: 'health', multiplier: 1.4 },
      { type: 'regen', hpPerTick: 5 },
    ],
    stackable: false,
  },

  // ─── SPORT SYNERGIES ──────────────────────────────────────────────────────

  {
    id: 'sport_5',
    name: 'Olympic Champion',
    description: '5 Sport: +30% Speed, +20% Attack',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'sport', minCount: 5 }],
    effects: [
      { type: 'stat_multiply', stat: 'speed', multiplier: 1.3 },
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.2 },
    ],
    stackable: false,
  },
  {
    id: 'olympics_3',
    name: 'Olympian Spirit',
    description: '3 Olympics: First Strike',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'olympics', minCount: 3 }],
    effects: [{ type: 'first_strike' }],
    stackable: false,
  },

  // ─── DISASTER & DISEASE ───────────────────────────────────────────────────

  {
    id: 'disaster_3',
    name: 'Cataclysm',
    description: '3 Disasters: AoE damage',
    tier: 'bronze',
    conditions: [{ type: 'has_tag', tag: 'disaster', minCount: 3 }],
    effects: [{ type: 'aoe_damage', damagePerTick: 8 }],
    stackable: false,
  },
  {
    id: 'disease_3',
    name: 'Plague Carrier',
    description: '3 Disease: DoT + AoE',
    tier: 'silver',
    conditions: [{ type: 'has_tag', tag: 'disease', minCount: 3 }],
    effects: [
      { type: 'aoe_damage', damagePerTick: 12 },
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.1 },
    ],
    stackable: false,
  },

  // ─── HYBRID / MULTI-DOMAIN COMBOS ─────────────────────────────────────────

  {
    id: 'animal_herbivore_tank',
    name: 'Nature Fortress',
    description: '5 Animals + 5 Herbivores: Tank build unlock (+60% Health)',
    tier: 'gold',
    conditions: [
      { type: 'has_tag', tag: 'animal', minCount: 5 },
      { type: 'has_tag', tag: 'herbivore', minCount: 5 },
    ],
    effects: [
      { type: 'stat_multiply', stat: 'health', multiplier: 1.6 },
      { type: 'regen', hpPerTick: 10 },
    ],
    stackable: false,
  },
  {
    id: 'human_war_military',
    name: 'Warlord Council',
    description: '3 Humans + 3 Military + 2 War: Dominant attack build',
    tier: 'gold',
    conditions: [
      { type: 'has_tag', tag: 'human', minCount: 3 },
      { type: 'has_tag', tag: 'military', minCount: 3 },
      { type: 'has_tag', tag: 'war', minCount: 2 },
    ],
    effects: [
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.6 },
      { type: 'crit_chance', chance: 0.2 },
    ],
    stackable: false,
  },
  {
    id: 'science_technology',
    name: 'Industrial Revolution',
    description: '3 Science + 2 Technology: +35% all stats',
    tier: 'gold',
    conditions: [
      { type: 'has_tag', tag: 'science', minCount: 3 },
      { type: 'has_tag', tag: 'technology', minCount: 2 },
    ],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.35 }],
    stackable: false,
  },
  {
    id: 'politics_economy_europe',
    name: 'Imperial Trade Empire',
    description: 'Politics + Economics + Europe: Massive coin gain + stats',
    tier: 'gold',
    conditions: [
      { type: 'has_tag', tag: 'politics', minCount: 2 },
      { type: 'has_tag', tag: 'economics', minCount: 2 },
      { type: 'has_tag', tag: 'europe', minCount: 1 },
    ],
    effects: [
      { type: 'coin_gain_per_battle', amount: 50 },
      { type: 'stat_multiply', stat: 'all', multiplier: 1.3 },
    ],
    stackable: false,
  },
  {
    id: 'religion_war',
    name: 'Crusade',
    description: '3 Religion + 3 War: +45% Attack, Shield',
    tier: 'gold',
    conditions: [
      { type: 'has_tag', tag: 'religion', minCount: 3 },
      { type: 'has_tag', tag: 'war', minCount: 3 },
    ],
    effects: [
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.45 },
      { type: 'shield', flatAmount: 300 },
    ],
    stackable: false,
  },
  {
    id: 'astronomy_5',
    name: 'Cosmic Power',
    description: '5 Astronomy: 2× CP multiplier',
    tier: 'gold',
    conditions: [{ type: 'has_tag', tag: 'astronomy', minCount: 5 }],
    effects: [{ type: 'cp_multiply', multiplier: 2.0 }],
    stackable: false,
  },
  {
    id: 'primate_human',
    name: 'Evolution',
    description: '3 Primates + 2 Humans: +25% all stats',
    tier: 'silver',
    conditions: [
      { type: 'has_tag', tag: 'primate', minCount: 3 },
      { type: 'has_tag', tag: 'human', minCount: 2 },
    ],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.25 }],
    stackable: false,
  },
  {
    id: 'all_same_region',
    name: 'Regional Unity',
    description: 'All 5 cards share any one region tag: +20% all stats',
    tier: 'bronze',
    conditions: [{ type: 'team_size', exact: 5 }],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.2 }],
    stackable: false,
  },
  {
    id: 'navy_air',
    name: 'Combined Arms',
    description: '2 Navy + 2 Aviation: +30% Attack, +20% Speed',
    tier: 'silver',
    conditions: [
      { type: 'has_tag', tag: 'navy', minCount: 2 },
      { type: 'has_tag', tag: 'aviation', minCount: 2 },
    ],
    effects: [
      { type: 'stat_multiply', stat: 'attack', multiplier: 1.3 },
      { type: 'stat_multiply', stat: 'speed', multiplier: 1.2 },
    ],
    stackable: false,
  },
  {
    id: 'literature_philosophy',
    name: 'Enlightenment',
    description: '3 Literature + 2 Philosophy: +20% all stats, Coin gain',
    tier: 'silver',
    conditions: [
      { type: 'has_tag', tag: 'literature', minCount: 3 },
      { type: 'has_tag', tag: 'philosophy', minCount: 2 },
    ],
    effects: [
      { type: 'stat_multiply', stat: 'all', multiplier: 1.2 },
      { type: 'coin_gain_per_battle', amount: 10 },
    ],
    stackable: false,
  },
  {
    id: 'full_team_5',
    name: 'Full Squad',
    description: 'Team of exactly 5: +5% all stats',
    tier: 'bronze',
    conditions: [{ type: 'team_size', exact: 5 }],
    effects: [{ type: 'stat_multiply', stat: 'all', multiplier: 1.05 }],
    stackable: false,
  },
];
